### ISSUE TITLE
Wrong timer started in timer3.c

### ISSUE THREAD

**Issue by blkhawk** [gicking/STM8_templates#2]
_Line 269: TIM1.CR1.reg.CEN = 1; // start the timer_

Should this be TIM3 maybe? Not sure I am trying to use your code with a STM8L152 maybe its different :)

**Comment by gicking** [comment]
hello blkhawk,

you are correct, sorry! I only started TIM3 routines over christmas and haven't tried it yet. But who would've guessed that my templates are actually used...  ;-)   Give me a minute for checking.

One more thing: I am not yet 100% sure which functions I want to implement for TIMx. Any wishes/ideas? Thanks in advance!

Georg 

PS: I think for the L-family you also have to enable each peripheral block. So far I'm using the S- and A-family. So please be extra careful

**Comment by blkhawk** [comment]
Well my brother gave me a PC speaker and it has an annoying bug - so no choice than to make my own firmware for it. The programming interface is conveniently located behind a easy to remove front panel.
Thanks for the comment about the peripheral blocks  this might explain some trouble i am having.

**Comment by gicking** [comment]
hello again,

what a mess! I found several more bugs, but now it should work - at least now the LED on the STM8S Discovery board dims nicely...

Thanks again for pointing out this bug and have a nice day!

Georg

PS: please let me know if/what you have to change for (which?) STM8L. Thanks in advance!

**Comment by blkhawk** [comment]
whoops crossed wires - did you by any chance fix the bit order in PCKENR1? If so please close the other issue. 

I also got my code working mainly changing the order of registers a bit and inserting a few missing ones. If you want to generalize your templates for STM8L you probably should make the order of the struct typedef configureable (maybe doing types for each register then assembling them per #define).
Before fixing the out of order issue with the periphial enabling I also switched your delay_ms code to be more in line with a STM example. (mainly just resetting UIF and then resetting it after the blocking part)

See the code here:
https://github.com/ezhov/stm8l-discovery/blob/master/discovery/Project/Discover/src/delay.c

**Comment by blkhawk** [comment]
I just merged your code and the timer works for me as well. I will be testing i2c, adc  as well as interrupts for my project.

**Comment by TG9541** [comment]
Sorry for crashing the party -  @RandoSY recently pointed me to this repository.  
@blkhawk: just out of interest, which kind of PC speaker has an STM8 µC?
@gicking: nice project!

**Comment by blkhawk** [comment]
@TG9541 an EDIFIER C2XD - if you look at a picture of it the translucent panel the 7-segment display is behind can be removed. A bit of black foam hides a 4-pin SWIM Interface. 
The rest of the insides are pretty nice as well (for a speaker at least):
https://cloud.schwanke.in/index.php/s/MJ8w9BRKLNZj34t
The TDA7303 Amp part is controlled over I2C.

**Comment by TG9541** [comment]
@blkhawk: that looks like a nice hacking project! Have fun! Maybe I'll treat myself to a kit some day.
It would be great if you could share your reverse-engineering results, and code as a GitHub project.

**Comment by gicking** [comment]
hi blkhawk,

do I understand correctly that I can close this issue for now? For a brief feedback thanks a lot in advance!

Georg

**Comment by blkhawk** [comment]
of course it was just hijacked by TG9541 :)

**Comment by gicking** [comment]
THX
