### ISSUE TITLE
Arduino 1.8.5.  Windows 10  compilation warnings 

### ISSUE THREAD

**Issue by suprimex** [gicking/STM8_templates#5]
Arduino 1.8.5.  Windows 10   - during compilation a bunch of  warnings :
bash.exe: warning: could not find /tmp, please create!

**Comment by gicking** [comment]
hello suprimex,

are you sure this issue report is in the correct repository? The "STM8_templates" provide example projects for STM8 and SDCC and Cosmic toolchains, not AVR/Arduino...?

However, if this is indeed the correct repo, could you please provide some more details? I just compiled a few projects under "Windows Vista Home Basic SP2" (sorry, no Win10, yet), and everything worked as expected. For your feedback thanks a lot in advance!

Regards, Georg

**Comment by gicking** [comment]
no response for >4 months, so I guess the issue is closed...!?
